export const aboutFigmaData = {
  hero: {
    title: "We are transforming how Pakistanis invest.",
    image: "/images/invest/about%20hero.webp",
  },
  intro: {
    eyebrow: "About Us",
    description:
      "We specialize in digital investing solutions that simplify saving, improve financial outcomes, and help Pakistanis build long-term wealth with confidence.",
  },
  metrics: [
    {
      value: "98%",
      label:
        "Clients achieve measurable ranking boosts and sustained SEO growth.",
    },
    {
      value: "500+",
      label:
        "High-impact campaigns optimized through advanced AI insights.",
    },
    {
      value: "$50M+",
      label:
        "Revenue gains generated by unlocking premium search visibility.",
    },
    {
      value: "70+",
      label: "Markets served with localized and data-backed SEO strategies.",
    },
  ],
  visibility: {
    eyebrow: "In the news",
    heading: "From Idea to Global Search Visibility Leader",
    trustedText: "Trusted by the best",
    logos: ["afterpay", "Framer", "pipedrive"],
    milestones: [
      {
        date: "2023 \u2022 November",
        title: "Global Expansion",
        description:
          "Scaled our platform to support multi-language SEO strategies, helping businesses worldwide improve visibility in their local markets.",
        image:
          "https://www.figma.com/api/mcp/asset/cc6dbd23-30e5-4a70-ae24-ae12dd3fa0c6",
      },
      {
        date: "2022 \u2022 June",
        title: "Automation and Insights",
        description:
          "Introduced advanced automation features, delivering real-time SEO recommendations and competitor tracking powered by machine learning.",
        image:
          "https://www.figma.com/api/mcp/asset/4826a836-acfc-4f0e-b297-58a29d0ca195",
      },
      {
        date: "2021 \u2022 August",
        title: "Alpha Release",
        description:
          "We launched our first working prototype, enabling early testers to experience AI-powered keyword analysis and search trend prediction.",
        image:
          "https://www.figma.com/api/mcp/asset/7712db3f-307e-4944-9a8e-3cfd38bbce42",
      },
    ],
  },
  testimonials: {
    eyebrow: "Testimonials",
    heading: "Meet our happy investors",
    items: [
      {
        label: "Tundra Fonder",
        quote:
          "Through stimulating private savings now, Pakistan can make sure that the state is not overwhelmed 30 years from now when the youth of today retire.",
        person: "Mattias Martinsson",
        role: "Co-founder of Tundra Fonder, Sweden",
        avatar: "/images/testimonials/Avatar2.png",
        companyLogo: "/images/testimonials/company2.png",
        tabLogo: "/images/testimonials/company2.png",
      },
      {
        label: "VEF",
        quote:
          "Mahaana is addressing one of the most important long-term financial issues that exist in Pakistan today. We are proud to back the CEO, Shamoon and his team in this scale venture and I am confident that Mahaana's success will be a positive for both the users of its platform and Pakistan as a whole.",
        person: "David Nangle",
        role: "CEO, VEF",
        avatar: "/images/testimonials/Avatar1.png",
        companyLogo: "/images/testimonials/company3.png",
        tabLogo: "/images/testimonials/company3.png",
      },
      {
        label: "IGI Holdings",
        quote:
          "IGI is more than a key investor and is a strategic local partner of Mahaana. There are clear synergies between IGI Insurance, IGI Securities and a digital wealth management company like Mahaana, which has a team with a proven track record of fund management in global markets.",
        person: "Tahir Masaud",
        role: "CEO, IGI Holdings",
        avatar: "/images/testimonials/Avatar3.png",
        companyLogo: "/images/testimonials/company2.png",
        tabLogo: "/images/testimonials/company1.png",
      },
    ],
  },
} as const;
